activitystreams.py, instagram.py, instagram_test.py
- instagram API allows creating comments and likes.
=> removing python-instagram dependency & support instagram publish

granary/facebook.py, granary/microformats2.py, granary/source.py, granary/test/test_facebook.py, granary/test/test_source.py, granary/test/testdata/note.as.json, granary/test/testdata/note.mf2.html, granary/test/testdata/note.mf2.json
...specifically, implements much of https://github.com/snarfed/bridgy/issues/51#issuecomment-136018857 (but not all). corresponds to snarfed/bridgy#465.
=> original post discovery v2.0

granary/source.py, granary/test/test_source.py
see snarfed/bridgy#469 for details. for snarfed/bridgy#51.
=> second half of big OPD refactoring for snarfed/bridgy#51

granary/flickr.py, granary/test/test_flickr.py, granary/twitter.py
- support for posting photos, comments, and faves
- now prefers path_alias when constructing user and photo ids
=> Flickr publish

granary/facebook.py, granary/test/test_facebook.py, requirements.txt
For https://github.com/snarfed/bridgy/issues/554
=> When there is an explicit title, send it to Facebook

granary/flickr.py, granary/test/test_flickr.py
fix for https://github.com/snarfed/bridgy/issues/317
=> flickr: publish location

granary/test/test_twitter.py, granary/twitter.py
for https://github.com/snarfed/bridgy/issues/317
confirmed working here https://twitter.com/kylewmahan/status/684920569641349120
=> Twitter: publish include location

README.md, granary/facebook.py, granary/source.py, granary/templates/index.html, granary/test/test_facebook.py, granary/test/test_source.py
still testing, but pretty much complete. whee!
https://developers.facebook.com/docs/apps/changelog#v2_6
snarfed/bridgy#496, snarfed/bridgy#433, snarfed/bridgy#626, snarfed/bridgy#512
=> migrate facebook API from v2.2 to v2.6

README.md
Sorry that it's 3 commits, but I was editing on the web interface and found them one after another. Maybe merge squashed?
=> some tiny fixes to the readme

granary/github.py
Per updates to https://developer.github.com/v4/enum/reactioncontent/ and https://developer.github.com/v3/reactions/#reaction-types, add 🚀👀 reacji to REACTIONS_GRAPHQL and REACTIONS_REST
FYI Bridgy Docs are updated for 🚀👀 reacji in this PR: https://github.com/snarfed/bridgy/pull/916
=> add 🚀👀 reacji

README.md, docs/index.rst
It probably makes sense for me to get this merged, then get it released, so it's the exact version from `master` at the time of upload :+1:
=> Update release instructions + release v3.0

granary/tests/test_reddit.py
Here is a test of the conversion from praw objects to activitystream objects.  I have written fake classes that contain the attributes needed from the praw models.
I could see that coveralls had dropped by 1% on the last merge.  How can I check if this gets it back up?
=> [reddit] test of user and submission conversion to activity stream objects

granary/reddit.py, granary/tests/test_reddit.py
I realized that these two pieces are required for bridgy to understand where to send its webmentions.  Adding them for getting bridgy PR https://github.com/snarfed/bridgy/pull/935 working.
=> [reddit] adding article tag inReplyTo attr

granary/reddit.py, granary/tests/test_reddit.py
Minor change. Prefer to return actual html of the comment rather than the markdown formatted version.
=> use html in reddit comment content and submission url lookups

granary/reddit.py
slight tweak to make reddit search an exact match sorted by newness.
=> add quotes and sort=new to praw search

granary/reddit.py
It's suspected that there will be a performance improvement from instantiating the praw API once and storing.  Haven't confirmed but figure it's a better practice anyway.
=>  persist praw reddit API object in Reddit object 

granary/reddit.py, granary/tests/test_reddit.py
=> [reddit] Provide `title`, `content` and `bookmark-of` properties if present on a post

static/demo.js
fixes https://github.com/snarfed/granary/security/code-scanning/1 and https://github.com/snarfed/granary/security/code-scanning/2
=> demo UI JS: sanitize more inputs

README.md
Hasn't had an underscore in the name since ec906b80 in 2015. 😉
=> Update README.md - remove artifact from rename 8 years ago 🙂

granary/bluesky.py, granary/tests/test_bluesky.py
Needed for URL canonicalization.
=> Handle profile URIs in at_uri_to_web_url

.gitignore, granary/bluesky.py, granary/tests/test_bluesky.py, granary/tests/testdata/comment_inreplyto_id.bsky-from-as.json
As discussed in https://github.com/snarfed/bridgy/issues/1580#issuecomment-1925314697
=> Get base object for Bluesky replies

granary/bluesky.py, granary/tests/test_bluesky.py
For https://github.com/snarfed/bridgy-fed/issues/1503. I mostly followed 31f698cfebe081735babb8bd522eaf30fd1e9f73 in reverse.
=> bluesky.from_as1: fallback to embed/link for audio attachments

granary/bluesky.py, granary/tests/test_bluesky.py, granary/tests/testdata/note_mastodon_with_video.bsky-from-as.json
For handling oversized/ too long videos. Needs more work based on the test failures... (Guess I'll sleep on it)
=> bluesky.from_as1: fallback to embed/link for video attachments with missing blob

granary/bluesky.py, granary/tests/test_bluesky.py
The suggestion from https://github.com/snarfed/bridgy-fed/issues/1597#issuecomment-2521088052
=> Bluesky.from_as1: convert standalone link to post at end of post into a quote
