snarfed/granary

activitystreams.py, granary/atom.py, granary/microformats2.py, granary/test/test_facebook.py, granary/test/test_instagram.py, granary/test/test_microformats2.py, granary/test/test_testdata.py, granary/test/test_twitter.py, granary/test/testdata/article_with_comments.mf2.html, granary/test/testdata/article_with_comments.mf2.json, granary/test/testdata/article_with_likes.mf2.html, granary/test/testdata/article_with_likes.mf2.json, granary/test/testdata/article_with_reposts.mf2.html, granary/test/testdata/article_with_reposts.mf2.json, granary/test/testdata/comment.mf2.html, granary/test/testdata/comment.mf2.json, granary/test/testdata/invite.mf2.html, granary/test/testdata/invite.mf2.json, granary/test/testdata/like.mf2.html, granary/test/testdata/like_multiple_urls.mf2.html, granary/test/testdata/note.mf2.html, granary/test/testdata/note.mf2.json, granary/test/testdata/repost.mf2.html, granary/test/testdata/repost.mf2.json, granary/test/testdata/repost_of_with_h_cite.mf2.html, granary/test/testdata/rsvp.mf2.html, granary/twitter.py, test_app.py
- Use activity itself rather than the object when available
- Retweets include original status as the object of the activity
- p-* u-* properties are treated as properties rather than types
- Assign h-cite when parsing a nested context (rather than h-entry)
- Atom conversion prepends "Shared a post by..." (or "Liked a post by...") to the rendered content
Fixes #42 and #44
=> Mf2 more robust parsing for activities

granary/atom.py, granary/microformats2.py, granary/test/test_testdata.py, granary/test/testdata/article_with_likes.mf2.html, granary/test/testdata/article_with_likes.mf2.json, granary/test/testdata/article_with_reposts.mf2.html, granary/test/testdata/article_with_reposts.mf2.json, granary/test/testdata/like.as-from-mf2.json, granary/test/testdata/like.mf2.html, granary/test/testdata/like.mf2.json, granary/test/testdata/like_multiple_urls.as-from-mf2.json, granary/test/testdata/like_multiple_urls.mf2.html, granary/test/testdata/like_multiple_urls.mf2.json, granary/test/testdata/repost.as-from-mf2.json, granary/test/testdata/repost.mf2.html, granary/test/testdata/repost.mf2.json
All I wanted to do was move the repost rendering into `render_content` so that we'd get the same HTML rendering in mf2 and Atom conversions without having to add special cases to both.
It ended up being more refactoring than I bargained for, but I'm happy with the result.
=> Mf2 moved repost context to render_content

granary/microformats2.py, granary/test/test_testdata.py, granary/test/testdata/article_with_comments.as-from-mf2.json, granary/test/testdata/article_with_likes.as-from-mf2.json, granary/test/testdata/article_with_reposts.as-from-mf2.json, granary/test/testdata/in_reply_to_with_h_cite.mf2-from-as.html, granary/test/testdata/in_reply_to_with_h_cite.mf2-from-as.json, granary/test/testdata/in_reply_to_with_h_cite.mf2-from-json.html, granary/test/testdata/nested_author.mf2-from-as.html, granary/test/testdata/nested_author.mf2-from-as.json, granary/test/testdata/nested_author.mf2-from-json.html, granary/test/testdata/nested_author.mf2.json, granary/test/testdata/note.as-from-mf2.json, granary/test/testdata/note_with_composite_photo.mf2-from-as.json, granary/test/testdata/repost_of_with_h_cite.mf2-from-as.html, granary/test/testdata/repost_of_with_h_cite.mf2-from-as.json, granary/test/testdata/repost_of_with_h_cite.mf2-from-json.html, granary/test/testdata/repost_of_with_h_cite.mf2.json
add support for new extensions that override the primary extension,
e.g. mf2-from-as.json will supersede mf2.json when converting object_to_json
=> testdata: support asymmetric conversions

granary/facebook.py, granary/flickr.py, granary/instagram.py, granary/source.py, granary/test/test_instagram.py, granary/test/test_source.py, granary/test/test_twitter.py, granary/twitter.py, requirements.txt
We produce it as HTML, and now we consume it as HTML.  This allows
more control over silo-specific formatting, but more importantly allows
us to implement silos that support HTML formatting (such as medium).
See also: https://github.com/snarfed/bridgy/pull/557
=> Process AS content as HTML

granary/microformats2.py, granary/test/test_microformats2.py
Converts .h-entry > .p-location.h-geo to a proper ActivityStreams object with a location
that has latitude and longitude.
In the AS1 spec, location doesn't really seem to be an "object" per se, but it seems
like a convenient simplification to treat it as one
=> Add latitude and longitude to mf2->AS object conversion

activitystreams.py, granary/atom.py, granary/templates/user_feed.atom, granary/test/test_atom.py, granary/test/test_facebook.py, granary/test/test_instagram.py, granary/test/test_twitter.py, test_activitystreams.py, test_app.py
hey @voxpelli @kylewm mind taking a look at this? specifically 6f540f7. i've actually deployed it to https://granary-demo.appspot.com/ so you can try it there. e.g.:
```sh
$ curl 'https://granary-demo.appspot.com/url?input=html&output=atom&url=https://snarfed.org/&hub=http://foo/bar'
...
<link rel="alternate" href="https://snarfed.org/" type="text/html" />
<link rel="self" href="https://granary-demo.appspot.com/url?input=html&amp;output=atom&amp;url=https://snarfed.org/&amp;hub=http://foo/bar" type="application/atom+xml" />
<link rel="hub" href="http://foo/bar" />
...
```
=> add hub= query param for atom output. fixes #53

granary/facebook.py, granary/test/test_facebook.py
they've never been officially supported, and they break Known permalinks (and i think at least one other CMS's) pretty badly. known as already migrated away from them. time to pull the plug!
=> facebook: drop support for See Original links. #368, #650

granary/facebook.py, granary/flickr.py, granary/instagram.py, granary/source.py, granary/test/test_facebook.py, granary/test/test_flickr.py, granary/test/test_twitter.py, granary/twitter.py
when this value is "maybe", include a link iff the content of the
post must be truncated, e.g. when posting to Twitter.
this is the default behavior of the brevity library -- permalinks
are automatically omitted if the tweet is <= 140 characters.
ref snarfed/bridgy#561
=> add support for bridgy_omit_link="maybe"

granary/facebook.py, granary/microformats2.py, granary/source.py, granary/templates/user_feed.atom, granary/test/test_facebook.py, granary/test/test_microformats2.py, granary/test/test_source.py
=> facebook reactions

granary/test/test_atom.py, granary/test/test_microformats2.py
- mf2util changed to follow /authorship more closely, breaking some assumptions
in our unittests
- Move p-author h-card inside of an h-entry or h-feed so that it is picked up
by the authorship algorithm
=> fix test regressions caused by changes to mf2util.find_author 

granary/test/test_twitter.py, requirements.txt
it now recognizes com.apple as a URL in the string com.apple.appstore
like Twitter does
=> upgrade brevity and add test to verify new behavior

requirements.txt
should fix https://github.com/snarfed/bridgy/issues/714
=> bump version of brevity dependency to get new TLDs

granary/facebook.py, granary/test/test_facebook.py
They did it again: new reacji on Facebook. The announcement can be found [here](https://newsroom.fb.com/news/2017/06/facebook-celebrates-pride-month/), and it's not only temporary, it's also based on location. I can't post them myself at the moment, and I haven't received one, but here's an example that has them: https://www.facebook.com/Israel.Gay.Tourists.Information/videos/634064940125826/
(via https://twitter.com/raymonmens/status/873434818016681985)
I based this on your commit to add Thankful (https://github.com/snarfed/granary/commit/5b53c3cf43e046ca29e1423072af96216ba412bc)
The Facebook-docs link you added there is now indeed updated with `PRIDE`.
https://developers.facebook.com/docs/graph-api/reference/post/reactions
I hope the 🏳️‍🌈 (rainbow flag) is ok, since it's an addition of …
=> add facebook pride reacji

granary/jsonfeed.py, granary/test/testdata/note.feed.json
Images are already included in an item’s `image` property but feed readers don’t (and shouldn’t) display this as part of the post itself. See #146.
I apologize that I haven’t actually tested this fix (nor updated the automated tests) since I wasn’t able to get the tests running locally after trying for a while.
=> JSON Feed: Include images in an item's "content_html" (fixes #146)

granary/jsonfeed.py, granary/test/test_jsonfeed.py, granary/test/testdata/article_with_attachment_image_list.feed-from-as.json, granary/test/testdata/article_with_attachment_stream_list.feed-from-as.json, granary/test/testdata/article_with_audio_video.feed-from-as.json, granary/test/testdata/note.feed-from-as.json
See #148.
This isn’t ready yet; I’m only opening a PR so that I can see the CI output.
=> Render JSON Feed entries’ content with render_content

.gitignore
To remove noise from diffs / `git status` as well as removing the risk
of accidentally committing these files, we should add this to our
`.gitignore`.
=> Gitignore compiled Python files

.gitignore, api.py, app.py, granary/meetup.py, granary/templates/index.html, granary/tests/test_meetup.py, setup.py
As part of snarfed/bridgy/issues/873 we want to add Meetup.com support
to Brid.gy.
Before we can do this, we need to onboard it to granary.
For now, all were adding is RSVP support, so we can't add that in the
Granary webapp, just the library.
Unfortunately we don't get a permalink / ID back from the RSVP endpoint,
so similar to the way that Granary's Facebook likes work, we create our
own "permalink".
=> Add RSVP library support for Meetup.com

granary/meetup.py, granary/tests/test_meetup.py
As part of snarfed/bridgy/issues/873, we need to implement this method
for Brid.gy to correctly determine the actor in use.
=>  Add missing Granary methods for Meetup

granary/meetup.py, granary/tests/test_meetup.py
While integrating this library with Brid.gy (as part of snarfed/bridgy#873) it was found that a few incorrect assumptions existed around formats of data.
=> Fix: Meetup library defects

granary/meetup.py, granary/tests/test_meetup.py
As found when snarfed was testing snarfed/bridgy#906 with his own
account, which doesn't have a photo associated, a image `None` tries to
get loaded.
We can instead render one of the default images to show the user has no
photo.
=> Fix: Handle `null` photos from the Meetup API

granary/meetup.py, granary/tests/test_meetup.py
As noted in snarfed/bridgy#906, this is required to better display the
RSVPs in the Bridgy publish UI.
=> Add `embed_post` for embedding the RSVP as HTML

granary/meetup.py, granary/tests/test_meetup.py
As noticed by snarfed in bridg#906, there may not be an `actor`, as the
source post may not contain the correct Microformats2 to describe it.
We can instead use the `url` of the post to de-duplicate it, as it
should be unique, and always present. But if it is not, it'll return an
error to ensure the author fixes their post.
=> Fix: Use the `url` of the post for the Meetup `rsvp-by-`

granary/meetup.py, granary/tests/test_meetup.py
However, the difficulty here is that this error is also returned in
cases where the `in-reply-to` is not set, so we need this error message
to cover both cases.
Closes #191.
=> Fix: Return better error when RSVPing to non Meetup event

granary/reddit.py, granary/tests/test_reddit.py, requirements.txt
See https://github.com/snarfed/bridgy/pull/935 and https://github.com/snarfed/oauth-dropins/pull/35.
In summary, [this line](https://github.com/snarfed/bridgy/blob/1597739f506daf36c9b3781816236462aee70000/models.py#L613) in bridgy assumes that the format of user_json from oauth-dropins will match the input to the granary object's `user_to_actor`.  This is not possible in the current implementation because user_to_actor is accepting a praw Redditor object.  So I've written a helper class to convert from Redditor to dictionary, and then user_to_actor operates on that dictionary.  `praw_to_actor` wraps the two helper functions.
=> Bridgy user_to_actor compatibility

granary/source.py, granary/tests/test_source.py
As part of [bridgy#880](https://github.com/snarfed/bridgy/issues/880), we added a check to ensure that we would not be
subject to Cross-Site Scripting attacks (XSS).
However, as noted in [bridgy#936](https://github.com/snarfed/bridgy/issues/936), a post that does contain HTML is still
being rejected.
The simplest way to get around this is to escape the HTML tags, so they
can be safely rendered.
Test data via https://stackoverflow.com/a/5072031 adding a new class
which embeds our `content` property.
Closes [bridgy#936](https://github.com/snarfed/bridgy/issues/936).
=> Fix: Escape HTML content before embedding in a post

granary/reddit.py, granary/tests/test_reddit.py
when a reddit account is not available praw throws a 404 error.  I was thinking that we could catch the 404 and just fill in the user with a generic "missing" account.  
Other alternative is to throw away the comment, but that doesn't seem ideal either.  Open to suggestions.
=> catch exception when redditor account is not available

granary/reddit.py, granary/tests/test_reddit.py
We currently rely on the returned objects from praw having certain attributes which are not necessarily guaranteed.  This change allows us to return empty objects if the praw objects are missing necessary attributes.
=> fixing missing is_subreddit attribute, adding tests for other missing attributes in praw objects

granary/source.py, granary/tests/test_source.py
Based on the discussion on https://github.com/snarfed/bridgy/issues/933, it seems that sometimes mastodon doesn't populate all of it's descendants immediately, which can lead to some inReplyTos being missed.  This PR changes `activity_changed` to pick up changes in the inReplyTo field and trigger. 
Regarding whether the new activity should replace or be merged in, it seems like it would be OK to just replace because the new activity ought to have all the inReplyTos associated with it (assuming they're all there on the mastodon side eventually).  Correct me if I'm missing something.
=> have activity_changed pick up when inReplyTo is changed

granary/tests/test_facebook.py, granary/tests/test_instagram.py
This PR relates to my bridgy issue open [here](https://github.com/snarfed/bridgy/issues/1099).
The purpose of this PR is to bring some of the tests for granary up to date with the new default user agent behaviour in webutil and oauth-dropins. In particular, Facebook and Instagram tests were failing since the browser-like user agent which was being used for scraping those two silos was not being set up properly and was causing an assert error in the `check_headers` helper method within the test utils module in webutil
I wasn't too sure if the original test behaviour may even have been wrong or whether I have completely misunderstood how the test works and now broken it. My solution was to inject the user-agent strings in the `expect_requests_get` helper class of each test class …
=> update unit tests to behave with oauth default user agent

README.md, granary/tests/test_twitter.py, granary/twitter.py
As noted in [0], Twitter alt text is getting pre-emptively trimmed.
This is a fixup for the original introduction in 9a61adc5, which did not
pass in a `words`, therefore the alt text is getting trimmed at the
default 14 words.
We can use 1000 words, as it's very unlikely to be met before 420
characters in the alt text.
[0]: https://github.com/snarfed/bridgy/issues/1175
=> Fix: Correctly trim Twitter alt text

granary/bluesky.py, granary/tests/test_bluesky.py, granary/tests/testdata/actor.as-from-bsky.json, granary/tests/testdata/actor.bsky.json, granary/tests/testdata/actor_with_featured.as-from-bsky.json, granary/tests/testdata/actor_with_featured.bsky.json, granary/tests/testdata/note.bsky-from-as.json, granary/tests/testdata/repost.as-from-bsky.json, granary/tests/testdata/repost.bsky-from-as.json, granary/tests/testdata/repost.bsky.json
As discussed - this simplifies the handling of (web) DIDs and handles somewhat to only support hostname-based handles and DIDs. It also attempts to parse the handle from the tag URI if all else fails. Tests are passing but I might have missed something!
=> Align handle/DID handling with AT Proto spec

granary/bluesky.py, granary/tests/test_bluesky.py, granary/tests/testdata/comment_inreplyto_id.bsky.json, granary/tests/testdata/note.bsky.json, granary/tests/testdata/quote.bsky.json, granary/tests/testdata/quote_and_attachment.bsky.json, granary/tests/testdata/quote_and_image.bsky.json, granary/tests/testdata/quote_with_image.bsky.json, granary/tests/testdata/repost.bsky.json
Bluesky doesn't actually use up/down votes (anymore?), it uses likes. This mostly just affects test data.
=> Replace upvote/downvote with likes in Bluesky

granary/bluesky.py, granary/tests/test_bluesky.py
This is the first bit needed to address https://github.com/snarfed/bridgy/issues/1575;  I wasn't sure if it was better to use the regex or simply match on provided handle parameter (currently unused)?
=> Add optional did replacement parameter to web_url_to_at_uri

granary/bluesky.py, granary/tests/test_bluesky.py
Fixes https://github.com/snarfed/bridgy/issues/1597
=> Fix cache in Bluesky

README.md, granary/rss.py, granary/tests/test_rss.py, granary/tests/testdata/feed_with_audio_video.as-from-rss.json, granary/tests/testdata/feed_with_audio_video.rss.xml, granary/tests/testdata/feed_with_note.as-from-rss.json, granary/tests/testdata/feed_with_note.rss.xml
I appreciate this project, thanks for your work on it!
Here's a change that I think will fix a few broken cases such as [this one](https://github.com/capjamesg/hugging-face-papers-rss/issues/3) that directly publish RSS converted from JSON feeds via granary.io.
In brief, we adhere closer to the RSS spec by removing the use of the default author email value `'-'` when constructing an RSS item.
(relevant upstream project code: https://github.com/lkiesow/python-feedgen/blob/v1.0.0/feedgen/entry.py#L366-L372)
https://granary.io/url?input=jsonfeed&output=rss&url=https://jamesg.blog/hf-papers.json
The above link produces an RSS file that at the time of writing is technically invalid when [checked](https://validator.w3.org/feed/#validate_by_input). This invalidity appears to break some RSS …
=> rss.from_as1: remove possible addition of invalid author element

granary/bluesky.py, granary/tests/test_bluesky.py
An attempt at fixing https://github.com/snarfed/bridgy-fed/issues/1163
=> bluesky.from_as1: preserve mentions of unresolved handles as links

granary/bluesky.py, granary/tests/test_bluesky.py
Extend #844 to videos. Haven't added anything to calculate these as `create` doesn't seem to support uploading videos.
=> bluesky.from_as1: set aspectRatio for videos too

granary/bluesky.py, granary/tests/test_bluesky.py
This is quite possibly a Bad Idea, but I've typed out the code so might as well open this.
My motivation here is that it's currently almost impossible to get a non-bridged users attention, but also that this is what would happen if you put the exact same text into a post using the bluesky app.
(This doesn't affect any existing tests, but I'm sure it'll have plenty of weird edge cases)
=> Bluesky.from_as1: extract any non-linked @-mention of a valid handle
